const places = [
    {
      image: require('../assets/places/1.png'),
      name: "French Quarter",
      address: "800 Decatur St, New Orleans, LA 70116",
      coordinates: [{ lat: 29.9584, lng: -90.0641 }],
      description: "The French Quarter, also known as Vieux Carré, is the oldest neighborhood in New Orleans, established in 1718. Its narrow streets are lined with Spanish-style architecture featuring wrought-iron balconies, vibrant courtyards, and colorful façades. Once a hub of colonial trade, the Quarter transformed over centuries into a melting pot of French, Spanish, African, and Creole cultures. Landmarks such as Jackson Square and the St. Louis Cathedral stand as symbols of the area's rich history. The district brims with life, offering jazz clubs, antique shops, and some of the city's finest cuisine. Night or day, the French Quarter exudes an intoxicating charm.",
      history: "This district embodies the origins of New Orleans, showcasing the city's colonial roots and cultural evolution. It's a designated National Historic Landmark.",
    },
    {
      image: require('../assets/places/2.png'),
      name: "St. Louis Cathedral",
      address: "615 Pere Antoine Alley, New Orleans, LA 70116",
      coordinates: [{ lat: 29.958, lng: -90.063 }],
      description: "St. Louis Cathedral is one of the most iconic landmarks in New Orleans, dominating Jackson Square with its towering spires. Established in 1720 and rebuilt multiple times, this Roman Catholic cathedral is the oldest of its kind in continuous use in the United States. Its interior boasts stunning stained glass windows, religious statues, and a tranquil atmosphere that invites reflection. The cathedral has witnessed historical moments, from colonial rule to the vibrant festivals of modern New Orleans. Its front courtyard is a favorite gathering spot for artists and musicians.",
      history: "A cornerstone of the city’s spiritual and architectural history, it symbolizes resilience and continuity in New Orleans.",
    },
    {
      image: require('../assets/places/3.png'),
      name: "Jackson Square",
      address: "701 Decatur St, New Orleans, LA 70116",
      coordinates: [{ lat: 29.9574, lng: -90.062 }],
      description: "Once called Place d'Armes, Jackson Square is a historical park that has been a central gathering place for over 300 years. Renamed in honor of Andrew Jackson after the Battle of New Orleans in 1815, the square is surrounded by historical structures, including the Cabildo and the Presbytère. Its beautifully manicured gardens and street artists create a lively yet serene atmosphere. Visitors can enjoy stunning views of the Mississippi River or explore the local crafts sold by artisans along its perimeter.",
      history: "A symbol of New Orleans' colonial and military history, Jackson Square was pivotal during Louisiana's transfer from France to the United States.",
    },
    {
      image: require('../assets/places/4.png'),
      name: "Bourbon Street",
      address: "Bourbon St, New Orleans, LA 70130",
      coordinates: [{ lat: 29.9592, lng: -90.0655 }],
      description: "Famed worldwide for its nightlife, Bourbon Street embodies the vibrant, unrestrained spirit of New Orleans. Established in 1721, the street is a mix of historic buildings and modern entertainment venues. Its bars, restaurants, and jazz clubs pulse with life day and night. The street becomes a carnival of music and festivities during Mardi Gras, but even on quieter days, it retains its unique allure. Balconies draped in beads and lights add to its captivating aesthetic.",
      history: "This street has been a center for Creole culture, music, and social gatherings since the early 18th century.",
    },
    {
      image: require('../assets/places/5.png'),
      name: "Garden District",
      address: "2727 Prytania St, New Orleans, LA 70130",
      coordinates: [{ lat: 29.9273, lng: -90.0846 }],
      description: "Known for its opulent mansions and lush greenery, the Garden District offers a glimpse into New Orleans' antebellum past. Originally developed in the 19th century for wealthy Americans who settled after the Louisiana Purchase, the district features Greek Revival, Italianate, and Victorian architecture. Tree-lined streets lead visitors to landmarks like Lafayette Cemetery No. 1 and the historic Commander’s Palace restaurant.",
      history: "A symbol of 19th-century prosperity, the Garden District reflects the cultural transition from French Creole to American influences.",
    },
    {
      image: require('../assets/places/6.png'),
      name: "Preservation Hall",
      address: "726 St. Peter St, New Orleans, LA 70116",
      coordinates: [{ lat: 29.9579, lng: -90.0645 }],
      description: "This unassuming music venue is a sanctuary for traditional New Orleans jazz. Opened in 1961, Preservation Hall continues to host live jazz performances nightly in a rustic, intimate setting. Its mission is to preserve and promote the city’s unique musical heritage. The hall has seen performances by legendary musicians and remains a key part of the local cultural fabric.",
      history: "A living museum of jazz, it’s a testament to the city’s deep-rooted musical traditions.",
    },
    {
      image: require('../assets/places/7.png'),
      name: "National WWII Museum",
      address: "945 Magazine St, New Orleans, LA 70130",
      coordinates: [{ lat: 29.9436, lng: -90.070 }],
      description: "This museum tells the story of the American experience during World War II. Through interactive exhibits, rare artifacts, and personal stories, visitors gain a deep understanding of the war’s global impact. Highlights include immersive theaters and a collection of wartime vehicles. Opened in 2000, it has since become a must-visit for history enthusiasts.",
      history: "A tribute to the bravery and sacrifices of the Greatest Generation, the museum holds a unique place in the national narrative.",
    },
    {
      image: require('../assets/places/8.png'),
      name: "Audubon Park",
      address: "6500 Magazine St, New Orleans, LA 70118",
      coordinates: [{ lat: 29.9265, lng: -90.1332 }],
      description: "This lush urban park offers a serene escape from the city’s hustle. Developed in 1871, Audubon Park features ancient oak trees, a lagoon, and pathways for walking or cycling. Its attractions include the Audubon Zoo and a golf course. The park is a favorite for picnics and leisurely strolls.",
      history: "Once the site of a plantation and later a Confederate camp, the park now symbolizes peace and community.",
    },
    {
      image: require('../assets/places/9.png'),
      name: "Lafayette Cemetery No. 1",
      address: "1400 Washington Ave, New Orleans, LA 70130",
      coordinates: [{ lat: 29.9285, lng: -90.0847 }],
      description: "One of the oldest cemeteries in the city, Lafayette Cemetery No. 1 was established in 1833. Its above-ground tombs and intricate mausoleums reflect New Orleans’ unique burial traditions. The cemetery has appeared in numerous films and novels, adding to its mystique.",
      history: "A cultural landmark, it tells stories of the city's past through its inscriptions and architecture.",
    },
    {
      image: require('../assets/places/10.png'),
      name: "Crescent City Connection",
      address: "Mississippi River Bridge, New Orleans, LA 70130",
      coordinates: [{ lat: 29.9407, lng: -90.0632 }],
      description: "This iconic twin-span bridge connects the east and west banks of New Orleans. Completed in 1958, it offers stunning views of the city skyline and the Mississippi River. At night, its illuminated structure adds to the city’s charm.",
      history: "A vital transportation link, it’s a modern symbol of New Orleans’ growth and resilience.",
    },
  ];
  
  export default places;
  